baseurl: ""
url: "https://mariuszz.com/"

title: Mariusz Z
email: mariusz+netlify@riseup.net
twitter_username: pulvish

# Build settings
strict_front_matter: true
profile: true

permalink: /:title

sass:
  style: compressed
  sass_dir: _sass

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
