baseurl: ""
url: "https://blog.vallode.com/"

title: Vallode
email: vallode@hotmail.co.uk
twitter_username: vallode_
gitlab_username:  vallode

# Build settings
strict_front_matter: true
profile: true

permalink: /:title

plugins:
  - jekyll-feed

sass:
  style: compressed
  sass_dir: _sass
