timezone: Europe/London
encoding: UTF-8
exclude: ['_drafts/']
permalink: /:title/
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# SEO
title: Mariusz Zarzycki
description: A freelance web developer with a focus on always learning
url: https://vallode.cf/
author: Mariusz Zarzycki
twitter:
  username: Vallode_
logo: /images/favicon.png