# https://www.getzola.org/documentation/getting-started/configuration/

base_url = "https://vallode.com/"
title = "vallode"
description = "Mariusz Z., web developer and learner."
default_language = "en"
compile_sass = true
minify_html = true
generate_feed = true
feed_filename = "rss.xml"
author = "vallode@riseup.net (vallode)"
build_search_index = false

[markdown]
highlight_code = false
render_emoji = true
smart_punctuation = true
lazy_async_image = true

[link_checker]
internal_level = "warn"

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"
paths_keep_dates = false

[extra]
