# https://www.getzola.org/documentation/getting-started/configuration/
# The URL the site will be built for
base_url = "https://vallode.com/"
title = "Vallode"

compile_sass = true
minify_html = true
highlight_code = false
build_search_index = false

[markdown]
smart_punctuation = false

[extra]
# Extra tid-bits used across the site.
currently_reading = "Small is Beautiful by E.F. Schumacher"
